name: vidstream_app
description: A minimal video streaming clone.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  go_router: ^13.0.0
  intl: ^0.19.0
  transparent_image: ^2.0.1
  cupertino_icons: ^1.0.2
  youtube_player_flutter: ^9.0.1
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
